#java:8 base image:
FROM java:8

COPY src /home/root/javahelloworld/src
#WORKDIR /home/root/javahelloworld
COPY bin  /home/root/javahelloworld/bin
WORKDIR /home/root/javahelloworld
RUN javac -d bin  src/HelloWorld.java
ENTRYPOINT ["java", "-cp" , "bin" , "HelloWorld"]
